Ser_Etiqueta/Models/DB/Factura.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Ser_Etiqueta.Models.DB
{
    public partial class Factura
    {
       

        public int KeyFactura { get; set; }
        public int? KeyCliente { get; set; }
        public int? IdEmpresa { get; set; }
        public int? IdSucursal { get; set; }
        public int KeyTipoFactura { get; set; } = 1;
        public int KeyFacturaEstatus { get; set; }
        public int NoFactura { get; set; }
        public decimal Subtotal { get; set; }
        public decimal IVA { get; set; }
        public decimal Total { get; set; }
        public DateTime FechaElaboracion { get; set; }
        public string UserName { get; set; }

        public DateTime CreateDate { get; set; }

        public int IsGeneraOT { get; set; }

        public int idSersa { get; set; }
        public string Prefijo { get; set; }
        public int? idOrdentrabajo { get; set; }



        //  public virtual ICollection<OrdenTrabajo> OrdenTrabajos { get; set; }
    }
}

Ser_Etiqueta/Models/DB/FacturaDetalle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Ser_Etiqueta.Models.DB
{
    public partial class FacturaDetalle
    {
        internal int keyDestino;

        public int KeyFacturaDetalle { get; set; }
        public int KeyFactura { get; set; }
        public int? KeyTipoPaquete { get; set; }
        public int? Cantidad { get; set; }
        public string DescripcionDetalle { get; set; }
        public decimal PrecioUnitario { get; set; }
        public int? KeyOrigen { get; set; }
        public int? KeyDestino { get; set; }
        public DateTime CreateDate { get; set; }
        public string Destinatario { get; set; }
       


    }
}

Ser_Etiqueta/Controllers/DepartamentoController.cs
using Microsoft.AspNetCore.Mvc;
using Ser_Etiqueta.Models.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ser_Etiqueta.Controllers 
{
   
    public class DepartamentoController : Controller
    {
        private readonly SERETIQUETASContext _context;
        public DepartamentoController(SERETIQUETASContext context)
        {
            this._context = context;
        }

        [HttpGet]
        public object getDepartamento()
        {

            IEnumerable<Departamento> listDepartamento = _context.Departamentos;
            return listDepartamento;
        }

        [HttpPost]
        public object getMunicipio(int keyDepto)
        {
            int key = 0;
            key = keyDepto;
            if (keyDepto == null || keyDepto == 0)
            {
                key = 1;
            }

            //   IEnumerable<Municipio> listMunnicipio = _context.Municipios;
            var listMunicipio = _context.Municipios.Where(p => p.KeyDepartamento == key);
            return listMunicipio;
        }


        public object getAllMunicipio()
        {


            //   IEnumerable<Municipio> listMunnicipio = _context.Municipios;
            var listMunicipio = _context.Municipios.ToList();
            return listMunicipio;
        }
    }
}

Ser_Etiqueta/Controllers/FacturaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using OfficeOpenXml;
using PdfSharp;
using PdfSharp.Drawing;
using PdfSharp.Drawing.Layout;
using PdfSharp.Pdf;
using QRCoder;
using Ser_Etiqueta.Areas.Identity.Data;
using Ser_Etiqueta.Models.DB;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Ser_Etiqueta.Controllers
{
    public class FacturaController : Controller
    {
        IWebHostEnvironment _env;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly SERETIQUETASContext _context;
        private readonly ILogger<ClienteController> _logger;
        private readonly IEmailSender _emailSender;

       

        public int IdSucursal { get; set; }
        public int IdEmpresa { get; set; }

        public int UltimoConsecutivo { get; set; }

        public string SerieCodigoEtiqueta { get; set; }

        public FacturaController(
         UserManager<ApplicationUser> userManager,
         SignInManager<ApplicationUser> signInManager,
         ILogger<ClienteController> logger,
         IEmailSender emailSender,
         SERETIQUETASContext context,
         IWebHostEnvironment env
         )
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _emailSender = emailSender;
            // this._usuarios = usuarios;
            this._context = context;
            _env = env;

        }
        [Authorize]
        [Authorize(Roles = "SuperAdmin,Facturacion")]
        public IActionResult Index()
        {
            var users = _userManager.Users.Where(p => p.Id == _userManager.GetUserId(User)).ToList();
            //  String usuario= _userManager.GetUserName(User);

            foreach (ApplicationUser user in users)
            {

                IdEmpresa = user.idEmpresa;
                IdSucursal = user.idSucursal;

                //  IdSucursal = user.idSucursal;

                /*  var thisViewModel = new UserRolesViewModel();
                  thisViewModel.UserId = user.Id;
                  thisViewModel.Email = user.Email;
                  thisViewModel.FirstName = user.FirstName;
                  thisViewModel.LastName = user.LastName;
                  thisViewModel.Roles = await GetUserRoles(user);
                  userRolesViewModel.Add(thisViewModel);*/
            }

            UsuariosInfo rec = new UsuariosInfo
            {
                idEmpresa = IdEmpresa,
                idSucursal = IdSucursal

            };
            return View(rec);
        }
        [HttpPost]
        public IActionResult generarOrden(int idEmpresa,int idSucursal,int noFactura)
        {
            getInfo();
            int count = 0;
            int keyCliente=0;
            int keyMunicipio=0;
            int keyDepartamento = 0;
            string etiqueta = "";
            string direccion = "";
            string codigoCliente = "";
            int keyDestino = 0;
            string prefijo = "";
            string codigoFactura = noFactura.ToString();

            codigoFactura.ToString().PadLeft(4, '0');

           
            OrdenTrabajo orden = new OrdenTrabajo()
            {
                IdEmpresa = idEmpresa,
                IdSucursal=idSucursal
            };
                _context.OrdenTrabajos.Add(orden);
               _context.SaveChanges();

           
            var objFactura = _context.Factura.Where(p => p.KeyFactura == noFactura).AsNoTracking().ToList();
            foreach (var Factura in objFactura) {
                keyCliente = Convert.ToInt32(Factura.KeyCliente);
                prefijo = Factura.Prefijo;

            }


            var objCliente = _context.Clientes.Where(p => p.IdCliente== keyCliente).AsNoTracking().ToList();
            foreach (var Cliente in objCliente)
            {
                direccion = Cliente.Direccion;
                codigoCliente = Cliente.Codigo;
            }

            var objFacturaDetalle = _context.FacturaDetalle.Where(p => p.KeyFactura == noFactura).AsNoTracking().ToList();
            foreach (var FacturaDetalle in objFacturaDetalle)
            {
                keyDestino = (int)FacturaDetalle.KeyDestino;
                var objMunicipio = _context.vw_Sersa_Destinos.Where(p => p.KeyDestino == FacturaDetalle.KeyDestino).AsNoTracking().ToList();
                foreach (var municipio in objMunicipio)
                {
  
                        keyMunicipio = municipio.KeyMunicipio;
                  

                }
                
                for (int i = 1; i <= FacturaDetalle.Cantidad; i++)
                {
                    count++;
                    OrdenTrabajoDetalle o = new OrdenTrabajoDetalle
                    {
                         
                        idCliente = keyCliente,
                        idMunicipio = keyMunicipio,
                        IdOrdenTrabajo=orden.IdOrdenTrabajo,
                        IdTipoPaquete = FacturaDetalle.KeyTipoPaquete,
                        direccion = FacturaDetalle.Destinatario,
                        CantidadBulto = 1,
                        Peso = 0.00m,
                        Factura=prefijo+"-"+ $"{noFactura:0000}",
                        Codigo= codigoCliente,
                        KeyOrigen = (int)FacturaDetalle.KeyOrigen,
                        keyDestino = (int)keyDestino
                    };

                    _context.OrdenTrabajoDetalles.Add(o);
                    _context.SaveChanges();


              
                    UltimoConsecutivo = UltimoConsecutivo + 1;
                    UltimoConsecutivo.ToString().PadLeft(8, '0');
                    UltimoConsecutivo.ToString("00000000");
                    UltimoConsecutivo.ToString("D4");
                    etiqueta = SerieCodigoEtiqueta + "-" + $"{UltimoConsecutivo:00000000}";
                    QRCodeGenerator _qrCode = new QRCodeGenerator();
                    QRCodeData _qrCodeData = _qrCode.CreateQrCode(etiqueta, QRCodeGenerator.ECCLevel.Q);
                    QRCode qrCode = new QRCode(_qrCodeData);
                    Bitmap qrCodeImage = qrCode.GetGraphic(20);

                    OrdenTrabajoCodigo codigo = new OrdenTrabajoCodigo
                    {

                        IdOtdetalle = o.IdOtdetalle,
                        CodigoSerie = etiqueta,
                        Serie = i + "/" + o.CantidadBulto,
                        Imagen = BitmapToBytesCode(qrCodeImage)

                    };
                    _context.OrdenTrabajoCodigos.Add(codigo);
                   _context.SaveChanges();
                    etiqueta = "";
                }
              

            }
            Factura factura = new Factura
            {
                KeyFactura = noFactura,
                IsGeneraOT = 1,
                idOrdentrabajo=orden.IdOrdenTrabajo

            };

              _context.Entry(factura).Property(p => p.IsGeneraOT).IsModified = true;
            _context.Entry(factura).Property(p => p.idOrdentrabajo).IsModified = true;
            _context.SaveChanges();
            Empresa cliente = new Empresa
            {
                IdEmpresa = IdEmpresa,
                UltimoConsecutivo = UltimoConsecutivo


            };
            _context.Attach(cliente);
            _context.Entry(cliente).Property(p => p.UltimoConsecutivo).IsModified = true;
            _context.SaveChanges();


            return Json(orden);
           
        }
        private static Byte[] BitmapToBytesCode(Bitmap image)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                image.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
                return stream.ToArray();
            }
        }
        [HttpPost]
        public IActionResult insertFactura(Factura factura)
        {     

           string Prefijo="";
            if (ModelState.IsValid) {
                getInfo();
                var p = _context.vw_Sersa_Clientes.Where(p => p.KeyCliente == factura.KeyCliente).AsNoTracking().ToList();
                var prefijo = _context.Sucursales.Where(p => p.IdSucursal == IdSucursal).AsNoTracking().ToList();
                foreach (var item in prefijo) {
                    Prefijo = item.codigoFactura;
                }

                
                factura.Prefijo = Prefijo;
                _context.Factura.Add(factura);
                _context.SaveChanges();
                factura.NoFactura = factura.KeyFactura;
                _context.Entry(factura).Property(p => p.NoFactura).IsModified = true;
                _context.SaveChanges();

                return Json("1");
                /*    var count = _context.Clientes
                .Where(o => o.Codigo == factura.KeyCliente.ToString())
                .Count();
                    if (count == 0)
                    {
                        foreach (var item in p)
                        {
                            Cliente cliente = new Cliente
                            {
                                Codigo = item.KeyCliente.ToString(),
                                IdEmpresa = IdEmpresa,
                                IdSucursal = IdSucursal,
                                NombreCliente = item.DescripcionCliente,
                                NombreComercial = item.NombreComercial,
                                Telefono = item.Telefono,
                                Contacto = "-",
                                Direccion = item.Direccion,

Ser_Etiqueta/Controllers/SucursalController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Ser_Etiqueta.Models.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ser_Etiqueta.Controllers
{
    public class SucursalController : Controller
    {
        private readonly SERETIQUETASContext _context;


        public SucursalController(SERETIQUETASContext context)
        {
            this._context = context;
        }
        [HttpPost]
        public object getSucursales(int? idEmpresa)
        {
            var listSucursales = _context.Sucursales.Where(p => p.IdEmpresa == idEmpresa);
            return listSucursales;
        }

        [HttpPost]
        public IActionResult insert(Sucursale sucursal)
        {

            if (ModelState.IsValid)
            {
                _context.Sucursales.Update(sucursal);
                _context.SaveChanges();
                return Json("1");
                //   TempData["Mensaje"] = "El libro se ha editado correctamente";
                //  return Json(ModelState);
            }
            else
            {
                return Json("Ocurrio un Error");
            }
            //  return PartialView("_EmpresaFormPartial", empresa);
        }

        [HttpPost]
        public IActionResult cargarSucursales()
        {

            var p = _context.SP_CRUD_Sucursal.FromSqlInterpolated($"exec [configuration].[SP_CRUD_Sucursales] null,null,null,null,null,null,null,'S',''");
            return Json(p);
        }
        [HttpPost]
        public IActionResult UpdateSucursal(Sucursale sucursal)
        {

            if (ModelState.IsValid)
            {
                _context.Attach(sucursal);
                _context.Entry(sucursal).Property(p => p.NombreSucursal).IsModified = true;
                _context.Entry(sucursal).Property(p => p.codigoFactura).IsModified = true;
                _context.Entry(sucursal).Property(p => p.IdEmpresa).IsModified = true;
                _context.Entry(sucursal).Property(p => p.IdDepartamento).IsModified = true;
                _context.Entry(sucursal).Property(p => p.IdMunicipio).IsModified = true;
         
                _context.SaveChanges();
                return Json("1");
                //   TempData["Mensaje"] = "El libro se ha editado correctamente";
                //  return Json(ModelState);
            }
            else
            {
                return Json("Ocurrio un Error");
            }
        }

        [HttpPost]
        public IActionResult GetSucursal(int? IdSucursal)
        {
            if (IdSucursal == null || IdSucursal == 0)
            {
                return NotFound();
            }
            //obtener libro
            var sucursal= _context.Sucursales.Find(IdSucursal);
            if (sucursal== null)
            {
                return NotFound();
            }

            return Json(sucursal);
        }

    }
}

Ser_Etiqueta/Controllers/TipoController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Ser_Etiqueta.Areas.Identity.Data;
using Ser_Etiqueta.Models.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ser_Etiqueta.Controllers
{
    public class TipoController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly SERETIQUETASContext _context;
        private readonly ILogger<ClienteController> _logger;
        private readonly IEmailSender _emailSender;

        public TipoController(
       UserManager<ApplicationUser> userManager,
       SignInManager<ApplicationUser> signInManager,
       ILogger<ClienteController> logger,
       IEmailSender emailSender,
       SERETIQUETASContext context
       )
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _emailSender = emailSender;
            // this._usuarios = usuarios;
            this._context = context;
        }
        public object TipoPaquetes()
        {
            var tipo = _context.TipoPaquetes.Where(p => p.IdTipoPaquete <=9).ToList();
            return tipo;
        }
    }
}

Ser_Etiqueta/Views/Factura/FacturaDetalle.cshtml
@using Ser_Etiqueta.Models
@model Ser_Etiqueta.Models.DB.UsuariosInfo
@{
    ViewData["Title"] = "Detalle de Factura";
}
@{

    var idEmpresa = Model.idEmpresa;
    var estado = ViewData["estado"];
    var estadoOT = ViewData["estadoOT"];
}
<h1 style="  color: #014377">Factura No. @ViewData["NoFactura"]</h1>
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <p class="m-0" style="   color: #014377">Los campos marcados con * son obligatorios</p>
            </div><!-- /.col -->
            <!--<div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home </a></li>
                    <li class="breadcrumb-item active">Ordenes</li>
                </ol>
            </div>-->
            <!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<div class="container-fluid">
    <div class="row">
        @if (Convert.ToInt16(estado) == 1)
        {
            <div class="col-md-6 col-md-offset-2">
                <section>
                    <h4></h4>
                    <hr />
                    <input type="hidden" id="ordenTrabajo" value="@ViewData["orden"]" />
                    <input type="hidden" id="idCliente" value="" />
                    <div class="col-sm-12">
                        <div class="form-group row">
                            @*<label for="nombreCliente" class="col-sm-3 col-form-label">Codigo*</label>
                                <div class="col-sm-9">
                                    <input type="text" class="form-control" placeholder="Codigo del cliente" id="Codigo" name="Codigo" >
                                </div>*@
                        </div>

                        <div class="form-group row">
                            <label for="nombreCliente" class="col-sm-3 col-form-label">Fecha de elaboracion</label>
                            <div class="col-sm-9">
                                <input type="date" class="form-control" placeholder="" id="nombreCliente" readonly value="@ViewData["fecha"]">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="nombreCliente" class="col-sm-3 col-form-label">Nombre Comercial</label>
                            <div class="col-sm-9">
                                <input type="text" class="form-control" placeholder="" id="nombreComercial" readonly value="@ViewData["cliente"]">
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="nombreCliente" class="col-sm-3 col-form-label">Direccion*</label>
                            <div class="col-sm-9">
                                <textarea type="text" class="form-control" placeholder="" id="Destinatario"></textarea>
                            </div>
                        </div>

                    </div>


                </section>
            </div>
        }
        <div class="col-md-6 col-md-offset-2">

            <section>
                <h4></h4>
                <hr />
                <div class="col-sm-12">


                    <div class="form-group row">
                        <label for="nombreCliente" class="col-sm-3 col-form-label">Origen</label>
                        <div class="col-sm-9">
                            <select class="form-control select2bs4" style="width: 100%;" id=keyOrigen name=keyOrigen>
                            </select>
                        </div>
                    </div>

                          <div class="form-group row">
                        <label for="nombreCliente" class="col-sm-3 col-form-label">Destino</label>
                        <div class="col-sm-9">
                            <select class="form-control select2bs4" style="width: 100%;" id=keyDestino name=keyDestino>
                            </select>
                        </div>
                    </div>

                    <div class='form-group row'>
                        <label for='nombreCliente' class='col-sm-3 col-form-label'> Tipo de paquete</label>
                        <div class='col-sm-9'>
                            <select class='form-control select2bs4' style='width: 100%;' id='tipoPaquete'> </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="nombreCliente" class="col-sm-3 col-form-label">Cantidad*</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" placeholder="Cantidad" id="cantidad" name="cantidad">
                        </div>
                    </div>
                    <div class='form-group row'>
                        <label class='col-sm-3 col-form-label'> Precio* </label>
                        <div class='col-sm-9'>
                            <input type='text' class='form-control' placeholder='Precio' id='precio' name='precio'>
                        </div>
                    </div>
                    <div id="detalle">

                    </div>


                    <div class="form-group">
                        <button type="button" id="agregar" class="btn col-12" style=" background: #014377; color:white" onclick="addNewEnvio()">Agregar envio</button>
                    </div>


                </div>
            </section>

        </div>
    </div>
    @if (Convert.ToInt16(estado) == 1 && Convert.ToInt16(estadoOT)==0)
    {
        <div class="row">
            <div class="col-sm-12">
                <div class="form-group" id="optOrden">
                    <button type="button" class="btn col-6 " style=" background: #014377; color:white; float: right;" onclick="GenerarOrden()">Generar Orden de trabajo</button>
                    <br />
                </div>


            </div>

        </div>
    }else if (Convert.ToInt16(estadoOT)==1){
        <div class="row">
                <div class="col-sm-12">
                    <div class="form-group" id="optOrden">
                        <button type="button" class="btn btn-block btn-outline-primary btn-flat col-6 " style=" background: white; color:#014377; float: right;" onclick="verOrden('@ViewData["idOrdenTrabajo"]')">Orden de trabajo: #@ViewData["idOrdenTrabajo"]</button>
                        <br />
                    </div>


                </div>

            </div>
    }
</div>

<div class="row">

    <div class="col-md-12">

        <table id=detalle class="table" style="width:100%">
            <thead class="thead-dark">
                <tr>


                    <th scope="col">#</th>
                    <th scope="col">Paquete</th>
                    <th scope="col">Origen</th>
                    <th scope="col">Destino</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Precio Unitario</th>
                    <th scope="col">Subtotal</th>
                    <th scope="col"></th>


                </tr>
            </thead>
            <tbody id=row>
                <tr>
                </tr>
            </tbody>
            <tfoot>

            </tfoot>
        </table>
    </div>
</div>
<div class="row">

    <div class="col-lg-8">
        <label style="float: right; margin-top: 0;">Sub-Total:</label>
    </div>
    <div class="col-lg-4">
        <input type="text" class="form-control" id="subtotal" name=subtotal value="0.00" required autocomplete="off" readonly style="float: right; margin-top: 0;">
    </div>
</div>
<div class="row">
    <div class="col-lg-8">
        <label style="float: right; margin-top: 0;">IVA (15%):</label>
    </div>
    <div class="col-lg-4">
        <input type="text" class="form-control" id="iva" name=iva value="0.15" required autocomplete="off" readonly style="float: right; margin-top: 0;">
    </div>
</div>

<div class="row">
    <div class="col-lg-8">
        <label style="float: right; margin-top: 0;">Total:</label>
    </div>
    <div class="col-lg-4">
        <input type="text" class="form-control" id="total" name=total value="0.00" required autocomplete="off" readonly style="float: right; margin-top: 0;">
    </div>
</div>





<script type="text/javascript">
    var urlDepartamento = "@Url.Action("getDepartamento", "Departamento")";
    var urlMunicipios = "@Url.Action("getAllMunicipio", "Departamento")";
    var idEmpresa = "@Model.idEmpresa";
    var idSucursal = "@Model.idSucursal";
        var idFactura = "@ViewData["NoFactura"]";
        var SerieCodigoEtiqueta = "@ViewData["serieCodigo"]";
        var Estado= "@estado";
         var idSersa = "@ViewData["idSersa"]";
    var urlInsert = "@Url.Action("generarOrden", "Factura")";
    var urlInsertDetalle = "@Url.Action("insertFacturaDetalle", "Factura")";
    var urlDeleteDetalle = "@Url.Action("deleteFacturaDetalle", "Factura")";
    var urlLoadDetalle  = "@Url.Action("loadFacturaDetalle", "Factura")";
    var urlTipoPaquetes = "@Url.Action("TipoPaquetes", "Tipo")";
    var urlForm = "@Url.Action("Form", "Cliente")";
    var urlLoad = "@Url.Action("cargarOrdenDetalle", "Orden")";
    var urlLoadSucursal = "@Url.Action("cargarSucursales", "Sucursal")";
        var urlGetCliente = "@Url.Action("GetClienteCodigo", "Cliente")";
        var urlGetClienteNombre = "@Url.Action("GetClienteNombre", "Cliente")";
    var urlGetSucursal = "@Url.Action("GetSucursal", "Sucursal")";
        var urlUpdate = "@Url.Action("UpdateCliente", "Cliente")";
        var urlDelete = "@Url.Action("eliminarOrden", "Orden")";
    var urlUpdateDetalle = "@Url.Action("updateFacturaDetalle", "Factura")";
    var urlUpload = "@Url.Action("cargarExcel", "Cliente")";
    var urlDestinos = "@Url.Action("cargarDestinos_Sersa", "Cliente")";
    var admin = "@User.IsInRole("SuperAdmin")";
     var urlClientes = "@Url.Action("cargarClientes", "Cliente")";
    $(function () {

            loadTipoPaquete();
            getDestinos(idSersa);
            
           // console.log(destino);
        });

</script>

<script src="~/adminlte/js/load_select.js"></script>
<script src="~/adminlte/js/Factura.js"></script>