Ser_Etiqueta/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using OfficeOpenXml;
using Ser_Etiqueta.Areas.Identity.Data;
using Ser_Etiqueta.Models.DB;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Ser_Etiqueta.Controllers
{
    public class ClienteController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly SERETIQUETASContext _context;
        private readonly SERSAContext sersa_context;
        private readonly ILogger<ClienteController> _logger;
        private readonly IEmailSender _emailSender;
        IWebHostEnvironment _env;
        public int IdSucursal { get; set; }
        public int IdEmpresa { get; set; }
        public int? UltimoConsecutivo { get; set; }


        public ClienteController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            ILogger<ClienteController> logger,
            IEmailSender emailSender,
            SERETIQUETASContext context,
            IWebHostEnvironment env,
            SERSAContext sersa_context
            )
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _emailSender = emailSender;
           // this._usuarios = usuarios;
            this._context = context;
            _env = env;
            this.sersa_context = sersa_context;
        }

        [Authorize]
        [Authorize(Roles = "SuperAdmin,Etiqueta,Facturacion")]
        public IActionResult Index()
        {
            var users = _userManager.Users.Where(p => p.Id== _userManager.GetUserId(User)).ToList();
            //  String usuario= _userManager.GetUserName(User);
           
            foreach (ApplicationUser user in users)
           {

                IdEmpresa = user.idEmpresa;
                IdSucursal = user.idSucursal;

              
            }
           
            UsuariosInfo rec = new UsuariosInfo
            {
                idEmpresa = IdEmpresa,
                idSucursal = IdSucursal

            };
            var idSersa = _context.Empresas.Where(p => p.IdEmpresa == IdEmpresa).AsNoTracking();
            foreach (var item in idSersa)
            {
                ViewData["idSersa"] = item.IdSersa;
            }
            return View(rec);
        }

        public IActionResult Form()
        {
            var model = new Cliente { };

            return PartialView("_ClienteFormPartial", model);
        }

        [HttpPost]
        public IActionResult insert(Cliente cliente)
        {

            if (ModelState.IsValid)
            {
                _context.Clientes.Update(cliente);
                _context.SaveChanges();
                return Json("1");
                //   TempData["Mensaje"] = "El libro se ha editado correctamente";
                //  return Json(ModelState);
            }
            else
            {
                return PartialView("_ClienteFormPartial", cliente);

            }
            //  return PartialView("_clienteFormPartial", cliente);
            
        }
        private void getInfo()
        {
            var users = _userManager.Users.Where(p => p.Id == _userManager.GetUserId(User)).ToList();
            //  String usuario= _userManager.GetUserName(User);

            foreach (ApplicationUser user in users)
            {

                IdEmpresa = user.idEmpresa;
                IdSucursal = user.idSucursal;

         
            }
        }
        [HttpPost]
        public IActionResult cargarClientes()
        {

            if (User.IsInRole("SuperAdmin"))
            {
                var p = _context.SP_CRUD_Clientes.FromSqlInterpolated($"exec [etiquetas].[SP_CRUD_Clientes] null,null,null,null,null,null,'S',''");
                return Json(p);
            }
            else
            {
                getInfo();
                var p = _context.SP_CRUD_Clientes.FromSqlInterpolated($"exec [etiquetas].[SP_CRUD_Clientes] null,{IdEmpresa},null,null,null,null,'S2',''");
                return Json(p);
            }
           
            
        }

        [HttpPost]
        public IActionResult cargarClientes_Sersa()
        {


            IEnumerable<vw_Sersa_Clientes> Clientes_Sersa = _context.vw_Sersa_Clientes;

            return  Json(Clientes_Sersa);
          

        }

        [HttpPost]
        public IActionResult cargarClientes_Sersa_etiqueta()
        {


            IEnumerable<vw_Sersa_Clientes> Clientes_Sersa = _context.vw_Sersa_Clientes;

            return Json(Clientes_Sersa);


        }


        [HttpPost]
        public IActionResult cargarDestinos_Sersa(int keyCliente)
        {


            var result = _context.vw_Sersa_Destinos.Where(p => p.KeyCliente == keyCliente).AsNoTracking();
            return Json(result);


        }


        [HttpPost]
        public IActionResult Destinos_Sersa()
        {

            getInfo();
            var sucursales = _context.Empresas.Where(p => p.IdEmpresa == IdEmpresa).AsNoTracking().ToList();
            foreach (var item in sucursales)
            {
                var result = _context.vw_Sersa_Destinos.Where(p => p.KeyCliente == item.IdSersa).AsNoTracking();
                return Json(result);
            }


            return Json("Ocurrio algun problema");

        }

        [HttpPost]
        public IActionResult crearDestinoSersa(Destinos des)
        {

            getInfo();
            var sucursales = _context.Empresas.Where(p => p.IdEmpresa == IdEmpresa).AsNoTracking().ToList();
            foreach (var item in sucursales)
            {
                des.KeyCliente = item.IdSersa;
                des.Activo = true;
                sersa_context.Destinos.Add(des);
                sersa_context.SaveChanges();
                //var result = _context.vw_Sersa_Destinos.Where(p => p.KeyCliente == item.IdSersa).AsNoTracking();
                return Json("1");
            }


            return Json("Ocurrio algun problema");

        }

        [HttpPost]
        public IActionResult GetCliente(int? IdCliente)
        {
            if (IdCliente == null || IdCliente == 0)
            {
                return NotFound();
            }
            //obtener libro
            var cliente = _context.Clientes.Find(IdCliente);
            if (cliente == null)
            {
                return NotFound();
            }

            return Json(cliente);
        }

        [HttpPost]
        public IActionResult GetClienteNombreComercial(string Nombre)
        {
            if (Nombre == null || Nombre == "")
            {
                return NotFound();
            }
            //obtener libro
            var cliente = _context.Clientes.Where(p => p.NombreComercial == Nombre).ToList();
            if (cliente == null)
            {
                return NotFound();
            }

            return Json(cliente);
        }

        [HttpPost]
        public IActionResult GetClienteCodigo(string? Codigo)
        {
            getInfo();
            if (Codigo == null || Codigo == "")
            {
                return NotFound();
            }
            //obtener libro
            var cliente = _context.Clientes.Where(p=>p.Codigo==Codigo && p.IdEmpresa == IdEmpresa && p.IdSucursal == IdSucursal).ToList();
            if (cliente == null)
            {
                return NotFound();
            }

            return Json(cliente);
        }

        [HttpPost]
        public IActionResult GetClienteNombre(string? Nombre)
        {
            if (Nombre == null || Nombre == "")
            {
                return NotFound();
            }
            //obtener libro
            var cliente = _context.Clientes.Where(p => p.NombreCliente == Nombre).ToList();
            if (cliente == null)
            {
                return NotFound();
            }

            return Json(cliente);
        }

        [HttpPost]
        public IActionResult Updatecliente(Cliente cliente)
        {

            if (ModelState.IsValid)
            {

                _context.Attach(cliente);
                _context.Entry(cliente).Property(p => p.NombreCliente).IsModified = true;
                _context.Entry(cliente).Property(p => p.NombreComercial).IsModified = true;
                _context.Entry(cliente).Property(p => p.Telefono).IsModified = true;
                _context.Entry(cliente).Property(p => p.Direccion).IsModified = true;
                _context.Entry(cliente).Property(p => p.Cargo).IsModified = true;
                _context.Entry(cliente).Property(p => p.Email).IsModified = true;
                _context.Entry(cliente).Property(p => p.Contacto).IsModified = true;
                _context.Entry(cliente).Property(p => p.Movil).IsModified = true;
                _context.Entry(cliente).Property(p => p.KeyDepartamento).IsModified = true;
                _context.Entry(cliente).Property(p => p.KeyMunicipio).IsModified = true;
                _context.Entry(cliente).Property(p => p.Codigo).IsModified = true;
                _context.SaveChanges();

                return Json("1");
                //   TempData["Mensaje"] = "El libro se ha editado correctamente";
                //  return Json(ModelState);
            }
            else
            {
                return PartialView("_ClienteFormPartial", cliente);
            }
            //  return PartialView("_clienteFormPartial", cliente);
        }

       

            [HttpPost]
        public async Task<IActionResult> cargarExcel(int Empresa,int Sucursal)

Ser_Etiqueta/Controllers/EmpresaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ser_Etiqueta.Models.DB;
using Microsoft.EntityFrameworkCore;
using Ser_Etiqueta.Areas.Identity.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using System.IO;

namespace Ser_Etiqueta.Controllers
{
    [Authorize]
    [Authorize(Roles = "SuperAdmin")]
    public class EmpresaController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly SERETIQUETASContext _context;

        [BindProperty]
        public InputModel Input { get; set; }

        public class InputModel
        {

            public int idLogo { get; set; }
            public string logoEmpresa { get; set; }


        }
        public EmpresaController(SERETIQUETASContext context)
        {
            this._context = context;
        }


        public IActionResult Index()
        {
           
            return View();
        }

        [HttpGet]
        public object getDepartamento()
        {

            IEnumerable<Departamento> listDepartamento = _context.Departamentos;
            return listDepartamento;
        }

        [HttpPost]
        public object getMunicipio(int keyDepto)
        {
            int key = 0;
            key = keyDepto;
            if (keyDepto == null || keyDepto == 0)
            {
                key=1;
            }

            //   IEnumerable<Municipio> listMunnicipio = _context.Municipios;
            var listMunicipio = _context.Municipios.Where(p=>p.KeyDepartamento==key);
            return listMunicipio;
        }

        [HttpPost]
        public IActionResult insert(Empresa empresa)
        {

            if (ModelState.IsValid)
            {
                _context.Empresas.Update(empresa);
                _context.SaveChanges();
                return Json("1");
                //   TempData["Mensaje"] = "El libro se ha editado correctamente";
                //  return Json(ModelState);
            }
            else
            {
                return PartialView("_EmpresaFormPartial", empresa);
            }
          //  return PartialView("_EmpresaFormPartial", empresa);
        }

        [HttpPost]
        public IActionResult getLogo( int IdEmpresa)
        {
            InputModel send = new InputModel();
            var logo = _context.LogoEmpresas.Where(p => p.IdEmpresa == IdEmpresa).AsNoTracking();
            foreach (var item in logo) {
               send.idLogo = item.IdLogo;
               send.logoEmpresa = Convert.ToBase64String(item.logoEmpresa);
              //  Input.logoEmpresa = item.logoEmpresa;
            }
            return Json(send);
        }

            [HttpPost]
        public IActionResult uploadLogo(ICollection<IFormFile> file, int IdEmpresa,int idLogo)
        {
            LogoEmpresa logo = new LogoEmpresa();
            var checkLogo = _context.LogoEmpresas.Where(p => p.IdLogo == idLogo).AsNoTracking();
            if (idLogo != null && idLogo>0 )
            {
                foreach (var files in file)
                {
                    if (files.Length > 0)
                    {
                        using (var ms = new MemoryStream())
                        {

                            files.CopyTo(ms);
                            var fileBytes = ms.ToArray();
                            logo.IdLogo = idLogo;
                            logo.IdEmpresa = IdEmpresa;
                            logo.logoEmpresa = fileBytes;
                            // string s = Convert.ToBase64String(fileBytes);
                            // act on the Base64 data
                            _context.Attach(logo);
                            _context.Entry(logo).Property(p => p.logoEmpresa).IsModified = true;

                            _context.SaveChanges();
                            return Json("1");
                        }
                    }
                }


            }
            else {
                foreach (var files in file)
                {
                    if (files.Length > 0)
                    {
                        using (var ms = new MemoryStream())
                        {

                            files.CopyTo(ms);
                            var fileBytes = ms.ToArray();
                            logo.IdEmpresa = IdEmpresa;
                            logo.logoEmpresa = fileBytes;
                            // string s = Convert.ToBase64String(fileBytes);
                            // act on the Base64 data
                            var save = _context.LogoEmpresas.Add(logo);
                            _context.SaveChanges();
                            return Json("1");
                        }
                    }
                }
            }
           

         


            return Json("");
            
        }
        [HttpPost]
        public IActionResult UpdateEmpresa(Empresa empresa)
        {

            if (ModelState.IsValid)
            {

                _context.Attach(empresa);
               
                _context.Entry(empresa).Property(p => p.NombreComercial).IsModified = true;
                _context.Entry(empresa).Property(p => p.NombreEmpresa).IsModified = true;
                _context.Entry(empresa).Property(p => p.SerieCodigoEtiqueta).IsModified = true;
                _context.Entry(empresa).Property(p => p.IdDepartamento).IsModified = true;
                _context.Entry(empresa).Property(p => p.IdMunicipio).IsModified = true;
                _context.Entry(empresa).Property(p => p.IdSersa).IsModified = true;
                _context.Entry(empresa).Property(p => p.TieneSucursal).IsModified = true;
                _context.SaveChanges();

                return Json("1");
                //   TempData["Mensaje"] = "El libro se ha editado correctamente";
                //  return Json(ModelState);
            }
            else
            {
                return PartialView("_EmpresaFormPartial", empresa);
            }
            //  return PartialView("_EmpresaFormPartial", empresa);
        }
        
        [HttpPost]
        public IActionResult cargarEmpresas()
        {

            var p = _context.SP_CRUD_EMPRESAS.FromSqlInterpolated($"exec [configuration].[SP_CRUD_Empresas] null,null,null,null,null,null,null,null,null,null,'S',''");
            return Json(p);
        }

            public IActionResult Form()
        {
            var model = new Empresa { };

            return PartialView("_EmpresaFormPartial", model);
        }

        [HttpPost]
        public IActionResult GetEmpresa(int? IdEmpresa)
        {
            if (IdEmpresa == null || IdEmpresa == 0)
            {
                return NotFound();
            }
            //obtener libro
            var empresa = _context.Empresas.Find(IdEmpresa);
            if (empresa == null)
            {
                return NotFound();
            }

            return Json(empresa);
        }

    }
}

Ser_Etiqueta/Views/Cliente/Index.cshtml
@using Ser_Etiqueta.Models
@model Ser_Etiqueta.Models.DB.UsuariosInfo
@{
    ViewData["Title"] = "Clientes";
}
@{
    var data = ViewBag.Message;
}
<h1 style="  color: #014377">@ViewData["Title"]</h1>
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0" style="   color: #014377">Registro de Clientes</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home </a></li>
                    <li class="breadcrumb-item active">Clientes</li>
                </ol>
            </div><!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->



<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header ui-sortable-handle" style="cursor: move;">
                <h3 class="card-title" style=" color: #014377;">
                    <i class="fas fa-dot-circle mr-1"></i>
                    Registros
                </h3>
                <div class="card-tools">
                    <ul class="nav nav-pills ml-auto">
                        <li class="nav-item">
                            <a class="nav-link active" href="#revenue-chart" data-toggle="tab" style="  background: #BB0423;">Registro de clientes</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link" href="#sales-chart" data-toggle="tab">Sucursales</a>
                        </li>*@
                    </ul>
                </div>
            </div><!-- /.card-header -->
            <div class="card-body">
                <div class="tab-content p-0">
                    <!-- Morris chart - Sales -->
                    <div class="chart tab-pane active" id="revenue-chart" style="position: relative; ">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <button type="button" class="btn col-12" style=" background: #014377; color:white" onclick="addNew()">Agregar nuevo</button>
                                </div>
                            </div>

                            <div class="col-md-6">
                                @if (User.IsInRole("SuperAdmin"))
                                {
                                    <div class="form-group">
                                        <label>Empresa </label>
                                        <select class="form-control select2bs4" style="width: 100%;" id=Empresa onchange="getSucursal(this.value)">
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label >Sucursal</label>
                                        <select class="form-control select2bs4" style="width: 100%;" id=Sucursal value="">
                                            @*<option value="0" selected>No tiene</option>*@
                                        </select>
                                    </div>

                                    <form id="frmupload" method="post" enctype="multipart/form-data">
                                        <div class="input-group mb-3">

                                            <div class="custom-file">
                                                <input type="file" class="custom-file-input" id="excel" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet">
                                                <label class="custom-file-label" for="customFile"></label>
                                            </div>
                                            <div class="input-group-append">
                                                <button class=" btn " type="submit" id=subir style=" color: white;background: #014377">
                                                    <i class="fas fa-arrow-alt-circle-up mr-1"></i> Cargar
                                                    &nbsp;<span id="cargando" class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                                                    <span class="sr-only">Loading...</span>
                                                </button>
                                            </div>

                                        </div>

                                    </form>
                                }
                            </div>
                        </div>
                        <div class="row">

                            <div class="col-md-12">

                                <table id="example" class="table table-striped table-bordered" style="width:100%">
                                    <thead>
                                        <tr>


                                            <th>Codigo</th>
                                            <th>Nombre del Cliente</th>
                                            <th>Nombre Comercial</th>
                                            <th>Departamento</th>
                                            <th>Municipio</th>
                                            <th>Direccion</th>
                                            <th></th>

                                        </tr>
                                    </thead>

                                    <tfoot>
                                        <tr>

                                            <th>Codigo</th>
                                            <th>Nombre del Cliente</th>
                                            <th>Nombre Comercial</th>
                                            <th>Departamento</th>
                                            <th>Municipio</th>
                                            <th>Direccion</th>
                                            <th></th>
                                        </tr>
                                    </tfoot>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div><!-- /.card-body -->
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header ui-sortable-handle" style="cursor: move;">
                <h3 class="card-title" style="color: #014377;">
                    <i class="fas fa-bus mr-1"></i>
                 Destinos
                </h3>
                <div class="card-tools">
                    <ul class="nav nav-pills ml-auto">
                        <li class="nav-item">
                            @*<a class="nav-link active" href="#revenue-chart" data-toggle="tab">Registro de empresas</a>*@
                        </li>
                        <li class="nav-item">
                            @*<a class="nav-link" href="#sales-chart" data-toggle="tab">Sucursales</a>*@
                        </li>
                    </ul>
                </div>
            </div><!-- /.card-header -->
            <div class="card-body">
                <div class="col-md-6">
                    <div class="form-group">
                        <input type="hidden"  id="idLogo"  value="0"/>
                        <label>Destinos Actuales</label>
                        <select class="form-control select2bs4" style="width: 100%;" id=Destino>
                        </select>
                    </div>
                 <h4 style="color:#014377">Nuevo Destino</h4>
                     <div class="form-group">
                        <label>Ddepartamento </label>
                        <select class="form-control select2bs4" style="width: 100%;" id=dDepartamento  onchange="getMunicipio(this.value,3)">
                        </select>
                    </div>
                 <div class="form-group">
                        <label>Municipio </label>
                        <select class="form-control select2bs4" style="width: 100%;" id=dMunicipio>
                        </select>
                    </div>
                    <div class="form-group">
                        <input type="text"  class="form-control" id="nDestino" placeholder="Nuevo destino"/>

                    </div>
                    <div class="form-group">
                        <button type="button" class="btn col-12" style="background:#014377; color:white;"  id="crearDestino">Crear nuevo destino</button>
                    </div>
                </div>
            </div><!-- /.card-body -->
        </div>

<div class="modal fade" id="modalCRUD" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body" style='overflow-y: auto; height:450px; '>
                <input type="hidden" id="idCliente"  value="">
                <div class="row" id="showfrm">



                </div>
                <div class="row">
                    <div class="col-12">

                        <div class="form-group">
                            <button type="button" class="btn btn-outline-primary col-12" id="btnGuardar">Guardar registro</button>
                        </div>
                    </div>


                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-warning" data-dismiss="modal">Cerrar</button>
            </div>

        </div>
    </div>
</div>



<script type="text/javascript">
    var urlDepartamento = "@Url.Action("getDepartamento", "Departamento")";
    var urlMunicipio = "@Url.Action("getMunicipio", "Departamento")";
    var idEmpresa = "@Model.idEmpresa";
    var idSucursal = "@Model.idSucursal";
    var urlInsert  = "@Url.Action("insert", "Cliente")";
    var urlInsertSucursal = "@Url.Action("insert", "Sucursal")";
    var urlForm = "@Url.Action("Form", "Cliente")";
    var urlLoad = "@Url.Action("cargarClientes", "Cliente")";
    var urlLoadSucursal = "@Url.Action("cargarSucursales", "Sucursal")";
    var urlGetCliente = "@Url.Action("GetCliente", "Cliente")";
    var urlGetSucursal = "@Url.Action("GetSucursal", "Sucursal")";
    var urlUpdate = "@Url.Action("UpdateCliente", "Cliente")";
    var urlUpdateSucursal = "@Url.Action("UpdateSucursal", "Sucursal")";
    var urlUpload = "@Url.Action("cargarExcel", "Cliente")";
    var urlCargarEmpresas = "@Url.Action("cargarEmpresas","Empresa")";
     var urlSucursal = "@Url.Action("getSucursales", "Sucursal")";;
     var urlDestinos = "@Url.Action("Destinos_Sersa", "Cliente")";
     var urlCrearDestino = "@Url.Action("crearDestinoSersa", "Cliente")";
     
</script>

<script src="~/adminlte/js/load_select.js"></script>
<script src="~/adminlte/js/Clientes.js"></script>