Ser_Etiqueta/Controllers/DepartamentoController.cs
using Microsoft.AspNetCore.Mvc;
using Ser_Etiqueta.Models.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ser_Etiqueta.Controllers 
{
   
    public class DepartamentoController : Controller
    {
        private readonly SERETIQUETASContext _context;
        public DepartamentoController(SERETIQUETASContext context)
        {
            this._context = context;
        }

        [HttpGet]
        public object getDepartamento()
        {

            IEnumerable<Departamento> listDepartamento = _context.Departamentos;
            return listDepartamento;
        }

        [HttpPost]
        public object getMunicipio(int keyDepto)
        {
            int key = 0;
            key = keyDepto;
            if (keyDepto == null || keyDepto == 0)
            {
                key = 1;
            }

            //   IEnumerable<Municipio> listMunnicipio = _context.Municipios;
            var listMunicipio = _context.Municipios.Where(p => p.KeyDepartamento == key);
            return listMunicipio;
        }


        public object getAllMunicipio()
        {


            //   IEnumerable<Municipio> listMunnicipio = _context.Municipios;
            var listMunicipio = _context.Municipios.ToList();
            return listMunicipio;
        }
    }
}

Ser_Etiqueta/Controllers/OrdenController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using OfficeOpenXml;
using PdfSharp.Drawing;
using PdfSharp.Drawing.Layout;
using PdfSharp.Pdf;
using QRCoder;
using Ser_Etiqueta.Areas.Identity.Data;
using Ser_Etiqueta.Models.DB;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Ser_Etiqueta.Controllers
{
    public class OrdenController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly SERETIQUETASContext _context;
        private readonly ILogger<ClienteController> _logger;
        private readonly IEmailSender _emailSender;
        IWebHostEnvironment _env;
        public int IdSucursal { get; set; }
        public int IdEmpresa { get; set; }

        public int UltimoConsecutivo { get; set; }

        public string SerieCodigoEtiqueta { get; set; }

        public OrdenController(
          UserManager<ApplicationUser> userManager,
          SignInManager<ApplicationUser> signInManager,
          ILogger<ClienteController> logger,
          IEmailSender emailSender,
          SERETIQUETASContext context,
          IWebHostEnvironment env
          )
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _emailSender = emailSender;
            // this._usuarios = usuarios;
            this._context = context;
            _env = env;
        }
        [Authorize]
        [Authorize(Roles = "SuperAdmin,Etiqueta,Facturacion")]
        public IActionResult Index()
        {
            var users = _userManager.Users.Where(p => p.Id == _userManager.GetUserId(User)).ToList();
            //  String usuario= _userManager.GetUserName(User);

            foreach (ApplicationUser user in users)
            {

                IdEmpresa = user.idEmpresa;
                IdSucursal = user.idSucursal;

                //  IdSucursal = user.idSucursal;

                /*  var thisViewModel = new UserRolesViewModel();
                  thisViewModel.UserId = user.Id;
                  thisViewModel.Email = user.Email;
                  thisViewModel.FirstName = user.FirstName;
                  thisViewModel.LastName = user.LastName;
                  thisViewModel.Roles = await GetUserRoles(user);
                  userRolesViewModel.Add(thisViewModel);*/
            }

            UsuariosInfo rec = new UsuariosInfo
            {
                idEmpresa = IdEmpresa,
                idSucursal = IdSucursal

            };
            return View(rec);
        }

        private void getInfo()
        {
            var users = _userManager.Users.Where(p => p.Id == _userManager.GetUserId(User)).ToList();
            //  String usuario= _userManager.GetUserName(User);
            
            foreach (ApplicationUser user in users)
            {

                IdEmpresa = user.idEmpresa;
                IdSucursal = user.idSucursal;


            }
            var codigo = _context.Empresas.Where(p => p.IdEmpresa == IdEmpresa).AsNoTracking().ToList() ;

            foreach (var emp in codigo)
            {

                SerieCodigoEtiqueta = emp.SerieCodigoEtiqueta;
                UltimoConsecutivo = Convert.ToInt32(emp.UltimoConsecutivo);



            }

         
        }

        [HttpPost]
        public IActionResult insert(OrdenTrabajo orden)
        {
            
            if (ModelState.IsValid)
            {
                orden.UserName = _userManager.GetUserName(User);
                _context.OrdenTrabajos.Add(orden);
                _context.SaveChanges();
                return Json("1");
                //   TempData["Mensaje"] = "El libro se ha editado correctamente";
                //  return Json(ModelState);
            }
            else
            {
                return Json(orden);

            }
            //  return PartialView("_clienteFormPartial", cliente);

        }

        [HttpPost]
        public IActionResult UpdateEstado(OrdenTrabajo orden)
        {

            if (ModelState.IsValid)
            {
                _context.Attach(orden);
                _context.Entry(orden).Property(p => p.estado).IsModified = true;
                _context.SaveChanges();
                return Json("1");
                //   TempData["Mensaje"] = "El libro se ha editado correctamente";
                //  return Json(ModelState);
            }
            else
            {
                return Json(orden);

            }
            //  return PartialView("_clienteFormPartial", cliente);

        }

        public class Detalle
        {

            public int? IdOrdenTrabajo { get; set; }

            public int? idCliente { get; set; }
            public string? Codigo { get; set; }
            public int? Factura { get; set; }
            public int? idMunicipio { get; set; }
            public string? IdTipoPaquete { get; set; }

            public string? direccion { get; set; }
            public int? CantidadBulto { get; set; }
            public string? Peso { get; set; }

            public int KeyOrigen { get; set; }

            public int keyDestino { get; set; }

        }

        [HttpPost]
        public object insertDetalleOrden(Detalle detalle)
        {
           
            string prefijo = "0000";
            string etiqueta = "";
          
            /*  string[] peso = detalle.Peso.ToString().Split(",", StringSplitOptions.RemoveEmptyEntries);
              string[] tipo = detalle.IdTipoPaquete.ToString().Split(",", StringSplitOptions.RemoveEmptyEntries);*/
            string peso = detalle.Peso.ToString();
            string tipo = detalle.IdTipoPaquete.ToString();
            int idOtd = 0;
            getInfo();
           

            for (int i=1;i<=detalle.CantidadBulto;i++)
            {
                OrdenTrabajoDetalle saveDetalle = new OrdenTrabajoDetalle
                {
                    IdOrdenTrabajo=detalle.IdOrdenTrabajo,
                    idCliente=detalle.idCliente,
                    Codigo=detalle.Codigo,
                    Factura=detalle.Factura.ToString(),
                    idMunicipio=detalle.idMunicipio,
                    IdTipoPaquete = Convert.ToInt16(tipo),
                    // IdTipoPaquete= Convert.ToInt16(tipo[i-1]),
                    direccion =detalle.direccion,
                    CantidadBulto=1,
                    Peso = Convert.ToDecimal(peso),
                    KeyOrigen=detalle.KeyOrigen,
                    keyDestino=detalle.keyDestino
                    //  Peso=Convert.ToInt16(peso[i-1])
                };
                _context.OrdenTrabajoDetalles.Add(saveDetalle);
                _context.SaveChanges();
                UltimoConsecutivo = UltimoConsecutivo + 1;
                UltimoConsecutivo.ToString().PadLeft(8, '0');
                UltimoConsecutivo.ToString("00000000");
                UltimoConsecutivo.ToString("D4");
                etiqueta = SerieCodigoEtiqueta + "-" + $"{UltimoConsecutivo:00000000}";
                QRCodeGenerator _qrCode = new QRCodeGenerator();
                QRCodeData _qrCodeData = _qrCode.CreateQrCode(etiqueta, QRCodeGenerator.ECCLevel.Q);
                QRCode qrCode = new QRCode(_qrCodeData);
                Bitmap qrCodeImage = qrCode.GetGraphic(20);

                OrdenTrabajoCodigo codigo = new OrdenTrabajoCodigo
                {
                   
                    IdOtdetalle = saveDetalle.IdOtdetalle,
                    CodigoSerie = etiqueta,
                    Serie=i+"/"+ detalle.CantidadBulto,
                    Imagen = BitmapToBytesCode(qrCodeImage)
                   
                };
                _context.OrdenTrabajoCodigos.Add(codigo);
                _context.SaveChanges();
                etiqueta = "";
            }

            Empresa cliente = new Empresa
            {
                IdEmpresa=IdEmpresa,
                UltimoConsecutivo=UltimoConsecutivo


            };
            _context.Attach(cliente);
            _context.Entry(cliente).Property(p => p.UltimoConsecutivo).IsModified = true;
            _context.SaveChanges();





            List<String> numbers = new List<String>();
                 string code = "E"; //Or "C"
                 for (int i = 0; i <= 2000; i++)
                 {
                     numbers.Add(String.Format("{0}{1:000}", code, i));
                 }



                return Json("1");

        }

        private static Byte[] BitmapToBytesCode(Bitmap image)
        {
            using (MemoryStream stream = new MemoryStream())
            {
                image.Save(stream, System.Drawing.Imaging.ImageFormat.Png);
                return stream.ToArray();
            }
        }
        [HttpPost]
        public IActionResult cargarOrdenes()
        {
          
            if (User.IsInRole("SuperAdmin"))
            {
                var p = _context.SP_CRUD_Ordenes.FromSqlInterpolated($"exec [etiquetas].[SP_CRUD_OrdenTrabajo] null,null,null,null,null,null,null,null,null,'S',''");
                return Json(p);
            }
            else
            {
                getInfo();
                var p = _context.SP_CRUD_Ordenes.FromSqlInterpolated($"exec [etiquetas].[SP_CRUD_OrdenTrabajo] {IdEmpresa},null,null,null,null,null,null,null,null,'S1',''");
                return Json(p);
            }


        }

        [HttpPost]
        public IActionResult Filtro(string fechaInicio,string fechaFinal)
        {

            if (User.IsInRole("SuperAdmin"))
            {

Ser_Etiqueta/Controllers/SucursalController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Ser_Etiqueta.Models.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ser_Etiqueta.Controllers
{
    public class SucursalController : Controller
    {
        private readonly SERETIQUETASContext _context;


        public SucursalController(SERETIQUETASContext context)
        {
            this._context = context;
        }
        [HttpPost]
        public object getSucursales(int? idEmpresa)
        {
            var listSucursales = _context.Sucursales.Where(p => p.IdEmpresa == idEmpresa);
            return listSucursales;
        }

        [HttpPost]
        public IActionResult insert(Sucursale sucursal)
        {

            if (ModelState.IsValid)
            {
                _context.Sucursales.Update(sucursal);
                _context.SaveChanges();
                return Json("1");
                //   TempData["Mensaje"] = "El libro se ha editado correctamente";
                //  return Json(ModelState);
            }
            else
            {
                return Json("Ocurrio un Error");
            }
            //  return PartialView("_EmpresaFormPartial", empresa);
        }

        [HttpPost]
        public IActionResult cargarSucursales()
        {

            var p = _context.SP_CRUD_Sucursal.FromSqlInterpolated($"exec [configuration].[SP_CRUD_Sucursales] null,null,null,null,null,null,null,'S',''");
            return Json(p);
        }
        [HttpPost]
        public IActionResult UpdateSucursal(Sucursale sucursal)
        {

            if (ModelState.IsValid)
            {
                _context.Attach(sucursal);
                _context.Entry(sucursal).Property(p => p.NombreSucursal).IsModified = true;
                _context.Entry(sucursal).Property(p => p.codigoFactura).IsModified = true;
                _context.Entry(sucursal).Property(p => p.IdEmpresa).IsModified = true;
                _context.Entry(sucursal).Property(p => p.IdDepartamento).IsModified = true;
                _context.Entry(sucursal).Property(p => p.IdMunicipio).IsModified = true;
         
                _context.SaveChanges();
                return Json("1");
                //   TempData["Mensaje"] = "El libro se ha editado correctamente";
                //  return Json(ModelState);
            }
            else
            {
                return Json("Ocurrio un Error");
            }
        }

        [HttpPost]
        public IActionResult GetSucursal(int? IdSucursal)
        {
            if (IdSucursal == null || IdSucursal == 0)
            {
                return NotFound();
            }
            //obtener libro
            var sucursal= _context.Sucursales.Find(IdSucursal);
            if (sucursal== null)
            {
                return NotFound();
            }

            return Json(sucursal);
        }

    }
}

Ser_Etiqueta/Controllers/TipoController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Ser_Etiqueta.Areas.Identity.Data;
using Ser_Etiqueta.Models.DB;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ser_Etiqueta.Controllers
{
    public class TipoController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly SERETIQUETASContext _context;
        private readonly ILogger<ClienteController> _logger;
        private readonly IEmailSender _emailSender;

        public TipoController(
       UserManager<ApplicationUser> userManager,
       SignInManager<ApplicationUser> signInManager,
       ILogger<ClienteController> logger,
       IEmailSender emailSender,
       SERETIQUETASContext context
       )
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = logger;
            _emailSender = emailSender;
            // this._usuarios = usuarios;
            this._context = context;
        }
        public object TipoPaquetes()
        {
            var tipo = _context.TipoPaquetes.Where(p => p.IdTipoPaquete <=9).ToList();
            return tipo;
        }
    }
}

Ser_Etiqueta/Views/Orden/OrdenDetalle.cshtml
@using Ser_Etiqueta.Models
@model Ser_Etiqueta.Models.DB.UsuariosInfo
@{
    ViewData["Title"] = "Ordenes";
}
@{
    var idEmpresa = Model.idEmpresa;
    var estado = ViewData["estado"];
}
<style>
    .ui-autocomplete {
        position: absolute;
        z-index: 1000;
        cursor: default;
        padding: 0;
        margin-top: 2px;
        list-style: none;
        background-color: #ffffff;
        border: 1px solid #ccc;
        -webkit-border-radius: 5px;
        -moz-border-radius: 5px;
        border-radius: 5px;
        -webkit-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
        -moz-box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
        box-shadow: 0 5px 10px rgba(0, 0, 0, 0.2);
    }

        .ui-autocomplete > li {
            padding: 3px 20px;
        }

            .ui-autocomplete > li.ui-state-focus {
                background-color: #DDD;
            }

    .ui-helper-hidden-accessible {
        display: none;
    }
</style>
<h1 style="  color: #014377">Remision #@ViewData["orden"]</h1>
<!-- Content Header (Page header) -->
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <p class="m-0" style="   color: #014377">Los campos marcados con * son obligatorios</p>
            </div><!-- /.col -->
            <!--<div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Home </a></li>
                    <li class="breadcrumb-item active">Ordenes</li>
                </ol>
            </div>-->
            <!-- /.col -->
        </div><!-- /.row -->
    </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<div class="container-fluid">
    <div class="row">
        @if (Convert.ToInt16(estado)==1) { 
        <div class="col-md-6 col-md-offset-2">
            <section>
                <h4></h4>
                <hr />
                <input type="hidden" id="ordenTrabajo" value="@ViewData["orden"]" />
                <input type="hidden" id="idCliente" value="" />
                <div class="col-sm-12">
                    <div class="form-group row">
                        <label for="nombreCliente" class="col-sm-3 col-form-label">Codigo*</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" placeholder="Codigo del cliente" id="Codigo" name="Codigo">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="nombreCliente" class="col-sm-3 col-form-label">Nombre del cliente</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control autocomplete" placeholder="Nombre del cliente" id="nombreCliente" >
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="nombreCliente" class="col-sm-3 col-form-label">Nombre Comercial</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" placeholder="Nombre Comercial" id="nombreComercial" >
                        </div>
                    </div>

                       <div class="form-group row">
                        <label for="Destinatario" class="col-sm-3 col-form-label">Destinatario</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" placeholder="Destinatario" id="Destinatario" value="-">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="nombreCliente" class="col-sm-3 col-form-label">Direccion*</label>
                        <div class="col-sm-9">
                            <textarea type="text" class="form-control" placeholder="" id="direccion"></textarea>
                        </div>
                    </div>

                </div>


            </section>
        </div>
        }
    <div class="col-md-6 col-md-offset-2">
        @if (Convert.ToInt16(estado) == 1)
        {
            <section>
                <h4></h4>
                <hr />
                <div class="col-sm-12">
                    <div class="form-group row">
                        <label for="nombreCliente" class="col-sm-3 col-form-label">Factura*</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" placeholder="Ingrese el # de factura" id="Factura" name="Factura">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="nombreCliente" class="col-sm-3 col-form-label">Origen</label>
                        <div class="col-sm-9">
                            <select class="form-control select2bs4" style="width: 100%;" id=keyOrigen name=keyOrigen>
                            </select>
                        </div>
                    </div>

                          <div class="form-group row">
                        <label for="nombreCliente" class="col-sm-3 col-form-label">Destino</label>
                        <div class="col-sm-9">
                            <select class="form-control select2bs4" style="width: 100%;" id=keyDestino name=keyDestino>
                            </select>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="nombreCliente" class="col-sm-3 col-form-label">Cantidad*</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" placeholder="Cantidad" id="cantidad" name="cantidad">
                        </div>
                    </div>
                    <div class='form-group row'>
                        <label for='nombreCliente' class='col-sm-3 col-form-label'> Tipo de paquete #</label>
                        <div class='col-sm-9'>
                            <select class='form-control select2bs4' style='width: 100%;' id='tipoPaquete1'> </select>
                        </div>
                    </div>
                    <div class='form-group row'>
                        <label class='col-sm-3 col-form-label'> Peso (kg) </label>
                        <div class='col-sm-9'>
                            <input type='text' class='form-control' placeholder='Peso(KG)' id='peso1' name='peso'>
                        </div>
                    </div>
                    <div id="detalle">

                    </div>


                    <div class="form-group">
                        <button type="button" id="agregar" class="btn col-12" style=" background: #014377; color:white" onclick="addNewEnvio()">Agregar envio</button>
                    </div>
                   
                  
                </div>
            </section>
        }
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12">
            <div class="form-group">
                <button type="button" class="btn col-6 " style=" background: #014377; color:white; float: right;" onclick="imprimirAllEnvio()">Imprimir Todas las etiquetas</button>
            <br />
            </div>


        </div>
       
    </div>
</div>
    <div class="row">

        <div class="col-md-12">

            <table id="example2" class="table table-striped table-bordered" style="width:100%">
                <thead>
                    <tr>


                        <th>#</th>
                        <th>Nombre cliente</th>
                        <th>Nombre Comercial</th>
                        <th>Factura</th>
                        <th>Municipio</th>
                        <th>Direccion</th>
                        <th>tipo</th>
                        <th>peso(Kg)</th>
                        <th>serie</th>
                        <th></th>

                    </tr>
                </thead>

                <tfoot>
                    <tr>

                        <th>#</th>
                        <th>Nombre cliente</th>
                        <th>Nombre Comercial</th>
                        <th>Factura</th>
                        <th>Municipio</th>
                        <th>Direccion</th>
                        <th>tipo</th>
                        <th>peso(Kg)</th>
                        <th>serie</th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>







    <script type="text/javascript">
    var urlDepartamento = "@Url.Action("getDepartamento", "Departamento")";
    var urlMunicipio = "@Url.Action("getAllMunicipio", "Departamento")";
        var idEmpresa = "@Model.idEmpresa";
        var idOrdenTrabajo = "@ViewData["orden"]";
        var idSersa = "@ViewData["idSersa"]";
        var SerieCodigoEtiqueta = "@ViewData["serieCodigo"]";
        var Estado= "@estado";
    var urlInsert  = "@Url.Action("insertDetalleOrden", "Orden")";
    var urlTipoPaquetes = "@Url.Action("TipoPaquetes", "Tipo")";
    var urlForm = "@Url.Action("Form", "Cliente")";
    var urlLoad = "@Url.Action("cargarOrdenDetalle", "Orden")";
    var urlLoadSucursal = "@Url.Action("cargarSucursales", "Sucursal")";
        var urlGetCliente = "@Url.Action("GetClienteCodigo", "Cliente")";
        var urlGetClienteNombre = "@Url.Action("GetClienteNombre", "Cliente")";
        var urlGetClienteNombreComercial = "@Url.Action("GetClienteNombreComercial", "Cliente")";
    var urlGetSucursal = "@Url.Action("GetSucursal", "Sucursal")";
        var urlUpdate = "@Url.Action("UpdateCliente", "Cliente")";
        var urlDelete = "@Url.Action("eliminarOrden", "Orden")";
    var urlUpdateSucursal = "@Url.Action("UpdateSucursal", "Sucursal")";
        var urlUpload = "@Url.Action("cargarExcel", "Cliente")";
         var urlDestinos = "@Url.Action("cargarDestinos_Sersa", "Cliente")";
        var urlClientes = "@Url.Action("cargarClientes", "Cliente")";
        var Tags = [];
        var TagsComercial = [];
       // console.log(idSersa)
        $(function () {
            loadTags();
            loadTipoPaquete();
        getDestinos(idSersa)

        });

    </script>

   <script src="~/adminlte/js/load_select.js"></script>
    <script src="~/adminlte/js/Ordenes.js"></script>