Ser_Etiqueta/Models/Libro.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Ser_Etiqueta.Models
{
    public class Libro
    {
      
            [Key]
            public int Id { get; set; }

            [Required(ErrorMessage = "El titulo es Obligatorio")]
            [StringLength(50, ErrorMessage = "El {0} debe ser al menos {2} y maximo {1} Caracteres", MinimumLength = 3)]
            public string Titulo { get; set; }

            [Required(ErrorMessage = "La descripcion es Obligatorio")]
            [StringLength(50, ErrorMessage = "El {0} debe ser al menos {2} y maximo {1} Caracteres", MinimumLength = 3)]
            public string Descripcion { get; set; }

            [Required(ErrorMessage = "La fecha es Obligatoria")]
            [DataType(DataType.Date)]
            [Display(Name = "Fecha de Lanzamiento")]
            public DateTime FechaLanzamiento { get; set; }

            [Required(ErrorMessage = "La descripcion es Obligatorio")]
            public string Autor { get; set; }

            [Required(ErrorMessage = "La descripcion es Obligatorio")]
            public int Precio { get; set; }
        }
    
}

Ser_Etiqueta/Controllers/LibrosController.cs
using Microsoft.AspNetCore.Mvc;
using Ser_Etiqueta.Data;
using Ser_Etiqueta.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ser_Etiqueta.Controllers
{
    public class LibrosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LibrosController(ApplicationDbContext context)
        {
            this._context = context;
        }
        public IActionResult Index()
        {
            IEnumerable<Libro> listLibros = _context.Libro;
            return View(listLibros);
        }

        public IActionResult Create()
        {
           
            return View();
        }

        [HttpPost]
        public IActionResult Create(Libro libro)
        {
            if (ModelState.IsValid) 
            {
                _context.Libro.Add(libro);
                _context.SaveChanges();

                TempData["Mensaje"] = "El libro se ha creado correctamente";
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpPost]
        public IActionResult Edit(Libro libro)
        {
            if (ModelState.IsValid)
            {
                _context.Libro.Update(libro);
                _context.SaveChanges();

                TempData["Mensaje"] = "El libro se ha editado correctamente";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id==0) {
                return NotFound();
            }
            //obtener libro
            var libro = _context.Libro.Find(id);
            if (libro == null)
            {
                return NotFound();
            }

            return View(libro);
        }

        [HttpGet]
        public object getData(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //obtener libro
            var libro = _context.Libro.Find(id);
            if (libro == null)
            {
                return NotFound();
            }

            return libro;
        }
    }
}

Ser_Etiqueta/Views/Libros/Create.cshtml
@model Ser_Etiqueta.Models.Libro;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_layout";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">

            <div class="row">
                <!-- left column -->
                <div class="col-md-6">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Formulario de libros</h3>
                        </div>
                        <!-- /.card-header -->
                        <form method="post"  id="ajaxForm">
                            @*<form method="post" asp-action="Create" id="ajaxForm">*@
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="card-body">
                                    <div class="form-group">
                                        <label for="exampleInputEmail1">Titulo</label>
                                        <input type="text" class="form-control" id="Titulo" name="titulo" placeholder="Ingresa el titulo" asp-for="Titulo">
                                        <span asp-validation-for="Titulo"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Descripcion</label>
                                        <input type="text" class="form-control" id="Descripcion" name="Descripcion" placeholder="Descripcion" asp-for="Descripcion">
                                        <span asp-validation-for="Descripcion"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Fecha de Lanzamiento</label>
                                        <input type="date" class="form-control" id="FechaLanzamiento" name="FechaLanzamiento" placeholder="Fecha" asp-for="FechaLanzamiento">
                                        <span asp-validation-for="FechaLanzamiento"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Autor</label>
                                        <input type="text" class="form-control" id="Autor" name="Autor" placeholder="Autor" asp-for="Autor">
                                        <span asp-validation-for="Autor"></span>
                                    </div>
                                    <div class="form-group">
                                        <label for="exampleInputPassword1">Precio</label>
                                        <input type="number" class="form-control" id="Precio" name="Precio" placeholder="Precio" asp-for="Precio">
                                        <span asp-validation-for="Precio"></span>
                                    </div>


                                </div>
                                <!-- /.card-body -->

                                <div class="card-footer">
                                    <button class="btn btn-primary" type="submit" id="SubmitBtn">Submit</button>
                                </div>
                            </form>


</div>
                    <!-- /.card -->

                </div>
                <!--/.col (right) -->
                <!-- form start -->

            </div>
        </div>
    </section>
</div>
@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

    <script type="text/javascript">

        $(function () {
            $("#AjaxForm").submit(function (e) {
                e.preventDefault();

                // Mostramos el Ajax Loader
                $("#AjaxLoader").show("fast");

                // Deshabilitamos el botón de Submit
                $("#SubmitBtn").prop("disabled", true);
               var data= $("#AjaxForm").serialize()
                $.ajax({    
                    url: "@Url.Action("Create", "Libros")", // Url
                    data: data,
                    type: "post"  // Verbo HTTP
                })
                // Se ejecuta si todo fue bien.
                .done(function (result) {
                    if (result != null) {

                        // Actualiza el resultado HTML
                      //  $("#PostList").html(result);

                        // Un pequeño esfecto especial ;)
                     //   $("#PostList .row").first().hide();
                     //   $("#PostList .row").first().slideToggle("fast");

                        // Limpia el formulario
                     //   $("#Comentario").val("");
                     //   $("#Nombre").val("");
                     //   $("#Email").val("");
                     //   $("#Titulo").val("");

                        // Escondemos el Ajax Loader
                     //   $("#AjaxLoader").hide("slow");

                        // Habilitamos el botón de Submit
                        $("#SubmitBtn").prop("disabled", false);

                        // Mostramos un mensaje de éxito.
                     //   $("#ExitoAlert").show("slow").delay(2000).hide("slow");
                    }
                })
                // Se ejecuta si se produjo un error.
                .fail(function (xhr, status, error) {
                    // Mostramos un mensaje de error.
                //    $("#ErrorAlert").show("slow").delay(2000).hide("slow");

                    // Escondemos el Ajax Loader
                  //  $("#AjaxLoader").hide("slow");

                    // Habilitamos el botón de Submit
                  //  $("#SubmitBtn").prop("disabled", false);
                })
                // Hacer algo siempre, haya sido exitosa o no.
                .always(function () {

                });
            });
        });
    </script>

}

Ser_Etiqueta/Views/Libros/Edit.cshtml
@model Ser_Etiqueta.Models.Libro;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_layout";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <section class="content">
        <div class="container-fluid">

            <div class="row">
                <!-- left column -->
                <div class="col-md-6">
                    <!-- general form elements -->
                    <div class="card card-primary">
                        <div class="card-header">
                            <h3 class="card-title">Editar libro</h3>
                        </div>
                        <!-- /.card-header -->
                        <form method="post" asp-action="Edit"  id="ajaxForm">
                            @*<form method="post" asp-action="Create" id="ajaxForm">*@
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" class="form-control" id="id" name="id" asp-for="Id">
                            <div class="card-body">
                                <div class="form-group">
                                    <label for="exampleInputEmail1">Titulo</label>
                                    <input type="text" class="form-control" id="Titulo" name="titulo" placeholder="Ingresa el titulo" asp-for="Titulo">
                                    <span asp-validation-for="Titulo"></span>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Descripcion</label>
                                    <input type="text" class="form-control" id="Descripcion" name="Descripcion" placeholder="Descripcion" asp-for="Descripcion">
                                    <span asp-validation-for="Descripcion"></span>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Fecha de Lanzamiento</label>
                                    <input type="date" class="form-control" id="FechaLanzamiento" name="FechaLanzamiento" placeholder="Fecha" asp-for="FechaLanzamiento">
                                    <span asp-validation-for="FechaLanzamiento"></span>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Autor</label>
                                    <input type="text" class="form-control" id="Autor" name="Autor" placeholder="Autor" asp-for="Autor">
                                    <span asp-validation-for="Autor"></span>
                                </div>
                                <div class="form-group">
                                    <label for="exampleInputPassword1">Precio</label>
                                    <input type="number" class="form-control" id="Precio" name="Precio" placeholder="Precio" asp-for="Precio">
                                    <span asp-validation-for="Precio"></span>
                                </div>


                            </div>
                            <!-- /.card-body -->

                            <div class="card-footer">
                                <button class="btn btn-primary" type="submit" id="SubmitBt">Editar</button>
                            </div>
                        </form>


</div>
                    <!-- /.card -->

                </div>
                <!--/.col (right) -->
                <!-- form start -->

            </div>
        </div>
    </section>
</div>
@section Scripts{

    @{
        <partial name="_ValidationScriptsPartial" />
    }

<script type="text/javascript">

    $("#SubmitBtn").click(function () {
                // Mostramos el Ajax Loader
                $("#AjaxLoader").show("fast");

                // Deshabilitamos el botón de Submit
                $("#SubmitBtn").prop("disabled", true);
               var data= $("#AjaxForm").serialize()
                $.ajax({
                    url: "@Url.Action("getData", "Libros")", // Url
                    data: {id:$("#id").val()},
                    type: "get"  // Verbo HTTP
                })
                // Se ejecuta si todo fue bien.
                .done(function (result) {
                    if (result != null) {
                        console.log(result)
                        // Actualiza el resultado HTML
                      //  $("#PostList").html(result);

                        // Un pequeño esfecto especial ;)
                     //   $("#PostList .row").first().hide();
                     //   $("#PostList .row").first().slideToggle("fast");

                        // Limpia el formulario
                     //   $("#Comentario").val("");
                     //   $("#Nombre").val("");
                     //   $("#Email").val("");
                     //   $("#Titulo").val("");

                        // Escondemos el Ajax Loader
                     //   $("#AjaxLoader").hide("slow");

                        // Habilitamos el botón de Submit
                        $("#SubmitBtn").prop("disabled", false);

                        // Mostramos un mensaje de éxito.
                     //   $("#ExitoAlert").show("slow").delay(2000).hide("slow");
                    }
                })
                // Se ejecuta si se produjo un error.
                .fail(function (xhr, status, error) {
                    // Mostramos un mensaje de error.
                //    $("#ErrorAlert").show("slow").delay(2000).hide("slow");

                    // Escondemos el Ajax Loader
                  //  $("#AjaxLoader").hide("slow");

                    // Habilitamos el botón de Submit
                  //  $("#SubmitBtn").prop("disabled", false);
                })
                // Hacer algo siempre, haya sido exitosa o no.
                .always(function () {

                });
            });
</script>

}

Ser_Etiqueta/Views/Libros/Index.cshtml
@model IEnumerable<Ser_Etiqueta.Models.Libro>;

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = "_Layout";
}


<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">

    @if (TempData["Mensaje"]!=null) 
    {
    <div class="alert alert-warning alert-dismissible fade show" role="alter">
        @TempData["Mensaje"]
        <button  type="button" class="close" data-dismiss="alter" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    }
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1>General Form</h1>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">General Form</li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
                <div class="row">
                    <!-- left column -->
                    <div class="col-md-6">
                        <!-- general form elements -->
                        <div class="card card-primary">
                            <div class="card-header">
                                <h3 class="card-title">Formulario de libros</h3>
                            </div>
                            <!-- /.card-header -->
                            <a asp-controller="Libros" asp-action="Create" class="btn btn-success">Crear Nuevo Libro</a>


                        </div>
                        <!-- /.card -->

                    </div>
                    <!--/.col (right) -->
     
            </div>
            <!-- /.row -->

                <div class="row">
                    <!-- left column -->
                    <div class="col-md-12">
                        <h3>Lista de Libros</h3>
                        @if (Model.Count() > 0)
                        {
                            <table class="table table-bordered table-striped">
                                <thead>
                                    <tr>
                                        <td>@Html.DisplayNameFor(m => m.Id)</td>
                                        <td>@Html.DisplayNameFor(m => m.Titulo)</td>
                                        <td>@Html.DisplayNameFor(m => m.Descripcion)</td>
                                        <td>@Html.DisplayNameFor(m => m.FechaLanzamiento)</td>
                                        <td>@Html.DisplayNameFor(m => m.Autor)</td>
                                        <td>@Html.DisplayNameFor(m => m.Precio)</td>
                                        <td>Acciones</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@item.Id</td>
                                            <td>@item.Titulo</td>
                                            <td>@item.Descripcion</td>
                                            <td>@item.FechaLanzamiento</td>
                                            <td>@item.Autor</td>
                                            <td>@item.Precio</td>
                
                                            <td>
                                                <a asp-controller="Libros" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Editar</a>
                                                <a asp-controller="Libros" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Eliminar</a>
                                            </td>

                                        </tr>


                                    }
                                </tbody>
                            </table>
                        }
                        else
                        {
                            <p>No existe Registro</p>
                        }
                    </div>
                    <!--/.col (right) -->
                </div>
            <!-- /.row -->
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
</div>
<!-- /.content-wrapper -->